name: Release new version on crates.io on release creation
on:
  release:
    types:
      - created
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
jobs:
  publish:
    strategy:
      matrix:
        toolchain:
          - stable
          # - beta
          # - nightly
        os:
          - ubuntu-latest
          # - windows-latest
          # - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          components: rustfmt, clippy
      - name: Publish on crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATESIO_REGISTRY_TOKEN }}
  compile:
    strategy:
      matrix:
        include:
          # Linux
          - target: "x86_64-unknown-linux-gnu"
            os: ubuntu-latest
            binary: recast
            toolchain: stable
          # Windows
          - target: "aarch64-pc-windows-msvc"
            os: windows-latest
            binary: recast.exe
            toolchain: stable
          - target: "x86_64-pc-windows-msvc"
            os: windows-latest
            binary: recast.exe
            toolchain: stable
          # macOS
          - target: "aarch64-apple-darwin"
            os: macos-latest
            binary: recast
            toolchain: stable
          - target: "x86_64-apple-darwin"
            os: macos-latest
            binary: recast
            toolchain: stable
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          components: rustfmt, clippy
          target: ${{ matrix.target }}
      - name: Compile binaries
        run: cargo build --release --target ${{ matrix.target }}
      - uses: actions/upload-artifact@v4
        with:
          name: recast-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/${{ matrix.binary }}
            target/completitions/*
      - name: Copy artifact
        run:
          cp target/${{ matrix.target }}/release/${{ matrix.binary }}
          target/recast-${{ matrix.target }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/recast-${{ matrix.target }}
            target/completitions/*
