name: Verify and test source
on:
  push:
    branches:
      - "*"
env:
  CARGO_TERM_COLOR: always
jobs:
  format:
    strategy:
      matrix:
        toolchain:
          - stable
          # - beta
          # - nightly
        os:
          - ubuntu-latest
          # - windows-latest
          # - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          components: rustfmt, clippy
      - name: Check format
        run: cargo fmt --all --check
  test:
    strategy:
      matrix:
        toolchain:
          - stable
          # - beta
          # - nightly
        os:
          - ubuntu-latest
          # - windows-latest
          # - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          components: rustfmt, clippy
      - name: Run tests
        run: cargo test --all-features --all-targets --workspace
  lint:
    strategy:
      matrix:
        toolchain:
          - stable
          # - beta
          # - nightly
        os:
          - ubuntu-latest
          # - windows-latest
          # - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          components: rustfmt, clippy
      - name: Run linter
        run: cargo clippy --all-features --all-targets --workspace
